### ISSUE TITLE
Allow to tag perks to plan out the future promotions

### ISSUE THREAD

**Issue by Iridar** [X2CommunityCore/X2CommunityPromotionScreen#53]
This idea came up a few times recently. The general idea is that while on the promotion screen, if the CPS is configured to show unreached ranks, players should be able to tag the unreached perks to plan the future ability tree of the soldier. Have to remember to also add controller support for this.

Tagging can be done by adding some sort of visual flag to the perk, or perhaps changing its color from grey to green or yellow.

This feature may or may not include automatic promotion functionality, where the pre-selected perk would be automatically chosen when the soldier is promoted.

**Comment by Iridar** [comment]
This is ready for review now.

**Comment by pledbrook** [comment]
@kdm2k6 As a controller user, wondering about how you think this should be handled? The issue is that pressing A on an unavailable ability (for example its rank is higher than the soldier's current rank or an ability at that rank has already been picked) currently both tags the ability *and* pops up the extra info for that ability.

I'm considering two options:

 1. Disable A from opening the extra ability info, since that's already accessible by left stick press
 2. Move the tagging to right stick press or some other option (X is currently Make Poster unfortunately)

I prefer the first option myself, but it breaks existing behaviour that players are likely already used to, so the second option seems the better one to me. What do you think? Do you have any other suggestions?

**Comment by kdm2k6** [comment]
I keep going back and forth while thinking about it.

I like option 1 because it allows you to quickly select certain abilities and tag other abilities; furthermore, the extra ability information is still available. I am uncertain about option 1 because it is "different"; it is difficult to say how long before it feels "normal". Additionally, I'm not sure if it will "get in the way" of people who don't wish to make use of the tagging feature.

I like option 2 because it maps the most common button, A, to 2 fundamental features : ability selection and ability information. Consequently, it separates "additional" functionality, the tagging system, via a different button press. The issue is that tagging with the right stick click could become cumbersome for people who use it a lot.

**Kind of a summary** : if you think a lot of people will make use of the tagging system I would go with option 1. However, if you believe people will generally use the promotion screen for ability selection and viewing, while tagging only occasionally, I would go with option 2.

**Comment by RustyDios** [comment]
I know it's not my place to say anything as a non-controller user .. but I like Option 3...
Have A do Ability Selection and Ability Information, both common use cases for the promotion UI and both tied to 'A'
Change X to do tagging .. as in 'X marks this spot', easy to remember and the next likely use case for the new screen
Implement R3/stick as the "Make Poster" button as I don't think it's used often enough -from the Promotion UI- to warrant it's existence there in the first place, but 'backwards compatibility' means it sort of needs to remain.

As long as it is apparent in the UI what each button does I don't think this is a major issue.

**Comment by kdm2k6** [comment]
I think this is a reasonable idea as well.

**Comment by Iridar** [comment]
The current implementation is "option 1, but only while the ragging system is enabled, vanilla behavior otherwise"
